const scores = [
  { partyPack: 1, game: "You Don't Know Jack", totalScore: 54, avgScore: 9.0 },
  { partyPack: 1, game: "Fibbage XL", totalScore: 45, avgScore: 7.5 },
  { partyPack: 1, game: "Drawful", totalScore: 31, avgScore: 5.2 },
  { partyPack: 1, game: "Word Spud", totalScore: 44, avgScore: 7.3 },
  { partyPack: 1, game: "Lie Swatter", totalScore: 36, avgScore: 6.0 },
  { partyPack: 2, game: "Fibbage 2", totalScore: 43, avgScore: 7.2 },
  { partyPack: 2, game: "Bidiots", totalScore: 44, avgScore: 7.3 },
  { partyPack: 2, game: "Earwax", totalScore: 44, avgScore: 7.3 },
  { partyPack: 2, game: "Quiplash XL", totalScore: 57, avgScore: 9.5 },
  { partyPack: 3, game: "Quiplash 2", totalScore: 58, avgScore: 9.7 },
  { partyPack: 3, game: "Trivia Murder Party", totalScore: 44, avgScore: 7.3 },
  { partyPack: 3, game: "Guesspionage", totalScore: 56, avgScore: 9.3 },
  { partyPack: 3, game: "Tee K.O.", totalScore: 48, avgScore: 8.0 },
  { partyPack: 4, game: "Fibbage 3", totalScore: 46, avgScore: 7.7 },
  { partyPack: 4, game: "Fibbage About You", totalScore: 53, avgScore: 8.8 },
  { partyPack: 4, game: "Survive The Internet", totalScore: 47, avgScore: 7.8 },
  { partyPack: 4, game: "Monster Seeking Monster", totalScore: 32, avgScore: 5.3 },
  { partyPack: 4, game: "Bracketeering", totalScore: 16, avgScore: 2.7 },
  { partyPack: 4, game: "Civic Doodle", totalScore: 19, avgScore: 3.2 },
  { partyPack: 5, game: "You Don't Know Jack - Full Stream", totalScore: 51, avgScore: 8.5 },
  { partyPack: 5, game: "Mad Verse City", totalScore: 48, avgScore: 8.0 },
  { partyPack: 5, game: "Split The Room", totalScore: 41, avgScore: 6.8 },
  { partyPack: 5, game: "Zeeple Dome", totalScore: 23, avgScore: 3.8 },
  { partyPack: 6, game: "Trivia Murder Party 2", totalScore: 45, avgScore: 7.5 },
  { partyPack: 6, game: "Role Models", totalScore: 47, avgScore: 7.8 },
  { partyPack: 6, game: "Joke Boat", totalScore: 35, avgScore: 5.8 },
  { partyPack: 6, game: "Dictionarium", totalScore: 24, avgScore: 4.0 },
  { partyPack: 6, game: "Push The Button (Adong Us)", totalScore: 29, avgScore: 4.8 },
  { partyPack: 7, game: "The Devil and the Details", totalScore: 43, avgScore: 7.2 },
  { partyPack: 7, game: "Champ'd Up", totalScore: 43, avgScore: 7.2, comment: "Hey, that's Mike's favourite game!" },
  { partyPack: 7, game: "Blather Round", totalScore: 57, avgScore: 9.5 },
  { partyPack: 7, game: "Quiplash 3", totalScore: 55, avgScore: 9.2 },
];
export default scores;